# Generated by Django 4.2.25 on 2025-11-06 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('capabilities', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_bar', models.FloatField()),
                ('completed_tasks', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer')], max_length=64)),
                ('subject', models.CharField(blank=True, max_length=128)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=32)),
                ('questions_count', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer')], max_length=32)),
                ('correct_answer', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='MindMateAPP.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('accuracy_percentage', models.FloatField()),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('study_level', models.CharField(choices=[('high_school', 'High School'), ('college', 'College')], max_length=32)),
                ('study_direction', models.CharField(max_length=128)),
                ('interests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Study Agent', max_length=128)),
                ('ocr_tool', models.CharField(default='Tesseract', max_length=128)),
                ('supported_formats', models.CharField(default='PDF,Image,Word', max_length=256)),
                ('ai_model', models.CharField(default='OpenAI GPT', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('word', 'Word Document'), ('text', 'Text')], max_length=64)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('original_filename', models.CharField(blank=True, max_length=256)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('content', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StudyPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MindMateAPP.studymaterial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.student')),
            ],
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MindMateAPP.studypipeline'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.student'),
        ),
        migrations.CreateModel(
            name='StudentPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_field_of_study', models.CharField(blank=True, help_text='e.g., Computer Science, Biology', max_length=256)),
                ('current_courses', models.TextField(blank=True, help_text='List of current courses, separated by commas')),
                ('preferred_learning_style', models.CharField(blank=True, choices=[('visual', 'Visual (learning through seeing)'), ('auditory', 'Auditory (learning through hearing)'), ('kinesthetic', 'Kinesthetic (learning through doing)'), ('reading_writing', 'Reading/Writing (learning through text)')], max_length=20)),
                ('daily_study_hours', models.FloatField(default=4.0, help_text='Typical daily study hours')),
                ('learning_goals', models.TextField(blank=True, help_text='e.g., Improve grades by 10%, learn a new coding language')),
                ('key_interests', models.TextField(blank=True, help_text='Comma-separated list of interests')),
                ('reminder_preferences', models.CharField(choices=[('email', 'Email'), ('push_notifications', 'Push Notifications'), ('in_app_alerts', 'In-app alerts'), ('sms', 'SMS'), ('none', 'No reminders')], default='in_app_alerts', max_length=20)),
                ('difficulty_preference', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('adaptive', 'Adaptive')], default='adaptive', help_text='Preferred difficulty level for generated content', max_length=20)),
                ('study_pace', models.CharField(choices=[('slow', 'Slow and steady'), ('moderate', 'Moderate pace'), ('fast', 'Fast-paced'), ('intensive', 'Intensive')], default='moderate', help_text='Preferred learning pace', max_length=20)),
                ('ai_interaction_style', models.CharField(choices=[('formal', 'Formal and professional'), ('friendly', 'Friendly and conversational'), ('motivational', 'Motivational and encouraging'), ('direct', 'Direct and to the point')], default='friendly', help_text='Preferred AI interaction style', max_length=20)),
                ('accessibility_needs', models.TextField(blank=True, help_text='Any special accessibility requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='MindMateAPP.student')),
            ],
            options={
                'verbose_name': 'Student Preference',
                'verbose_name_plural': 'Student Preferences',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('points_earned', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.quizquestion')),
                ('quiz_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='MindMateAPP.quizresult')),
            ],
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_count', models.IntegerField()),
                ('last_day', models.DateField()),
                ('progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.progress')),
            ],
        ),
        migrations.AddField(
            model_name='quizresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.student'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='generated_from_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MindMateAPP.studymaterial'),
        ),
        migrations.CreateModel(
            name='ProgressAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_time', models.DateTimeField()),
                ('results', models.TextField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.chatbot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.student')),
            ],
        ),
        migrations.AddField(
            model_name='progress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.student'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('reminder', 'Reminder'), ('achievement', 'Achievement'), ('suggestion', 'Suggestion')], max_length=32)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.student')),
            ],
        ),
        migrations.CreateModel(
            name='NextStudyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_for', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=32)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MindMateAPP.studymaterial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.student')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('assigned_at', models.DateField()),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MindMateAPP.studymaterial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.student')),
            ],
        ),
        migrations.CreateModel(
            name='EventPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_time', models.DateTimeField()),
                ('rationale', models.TextField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.chatbot')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.calendarevent')),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_type', models.CharField(choices=[('study_agent', 'Study Agent'), ('time_agent', 'Time Agent'), ('organization', 'Organization Bot')], max_length=32)),
                ('event_action', models.CharField(max_length=128)),
                ('message_content', models.TextField()),
                ('response_content', models.TextField(blank=True)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.student')),
            ],
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.student'),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('received_at', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.student')),
            ],
        ),
        migrations.CreateModel(
            name='Accuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindMateAPP.progress')),
            ],
        ),
    ]
