# Generated by Django 4.2.25 on 2025-11-05 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MindMateAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_field_of_study', models.CharField(blank=True, help_text='e.g., Computer Science, Biology', max_length=256)),
                ('current_courses', models.TextField(blank=True, help_text='List of current courses, separated by commas')),
                ('preferred_learning_style', models.CharField(blank=True, choices=[('visual', 'Visual (learning through seeing)'), ('auditory', 'Auditory (learning through hearing)'), ('kinesthetic', 'Kinesthetic (learning through doing)'), ('reading_writing', 'Reading/Writing (learning through text)')], max_length=20)),
                ('daily_study_hours', models.FloatField(default=4.0, help_text='Typical daily study hours')),
                ('learning_goals', models.TextField(blank=True, help_text='e.g., Improve grades by 10%, learn a new coding language')),
                ('key_interests', models.TextField(blank=True, help_text='Comma-separated list of interests')),
                ('reminder_preferences', models.CharField(choices=[('email', 'Email'), ('push_notifications', 'Push Notifications'), ('in_app_alerts', 'In-app alerts'), ('sms', 'SMS'), ('none', 'No reminders')], default='in_app_alerts', max_length=20)),
                ('difficulty_preference', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('adaptive', 'Adaptive')], default='adaptive', help_text='Preferred difficulty level for generated content', max_length=20)),
                ('study_pace', models.CharField(choices=[('slow', 'Slow and steady'), ('moderate', 'Moderate pace'), ('fast', 'Fast-paced'), ('intensive', 'Intensive')], default='moderate', help_text='Preferred learning pace', max_length=20)),
                ('ai_interaction_style', models.CharField(choices=[('formal', 'Formal and professional'), ('friendly', 'Friendly and conversational'), ('motivational', 'Motivational and encouraging'), ('direct', 'Direct and to the point')], default='friendly', help_text='Preferred AI interaction style', max_length=20)),
                ('accessibility_needs', models.TextField(blank=True, help_text='Any special accessibility requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='MindMateAPP.student')),
            ],
            options={
                'verbose_name': 'Student Preference',
                'verbose_name_plural': 'Student Preferences',
            },
        ),
    ]
