# Generated by Django 4.2.27 on 2025-12-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindMateAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='vector_collection_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
