# Generated by Django 4.2.26 on 2025-11-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindMateAPP', '0002_studymaterial_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
