# Generated by Django 5.2.3 on 2026-01-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindMateAPP', '0002_studymaterial_vector_collection_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_type', models.CharField(choices=[('study_agent', 'Study Agent'), ('time_agent', 'Time Agent'), ('organization', 'Organization Bot')], default='study_agent', max_length=32)),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='MindMateAPP.student')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['student', 'bot_type', '-updated_at'], name='MindMateAPP_student_25ae12_idx'), models.Index(fields=['session_id'], name='MindMateAPP_session_2d2b3a_idx')],
            },
        ),
    ]
