# Generated by Django 4.2.26 on 2025-11-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindMateAPP', '0003_calendarevent_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(default='#4285f4', max_length=7),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('study_session', 'Study Session'), ('exam', 'Exam'), ('homework_deadline', 'Homework Deadline'), ('personal', 'Personal Event')], default='personal', max_length=20),
        ),
    ]
