# Generated by Django 4.2.26 on 2025-11-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MindMateAPP', '0004_calendarevent_color_calendarevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEstimationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField(help_text='Natural language description of the task')),
                ('task_type', models.CharField(choices=[('study', 'Study Session'), ('exam', 'Exam Preparation'), ('quiz', 'Quiz Preparation'), ('homework', 'Homework'), ('assignment', 'Assignment'), ('project', 'Project Work'), ('reading', 'Reading'), ('research', 'Research'), ('writing', 'Writing'), ('practice', 'Practice'), ('other', 'Other')], default='study', max_length=32)),
                ('subject_area', models.CharField(blank=True, help_text='e.g., Mathematics, Biology, Computer Science', max_length=128)),
                ('estimated_hours', models.FloatField(help_text='Estimated completion time in hours')),
                ('confidence_score', models.FloatField(default=0.5, help_text='Confidence level (0.0 to 1.0)')),
                ('estimation_method', models.CharField(default='hybrid', help_text='Method used for estimation', max_length=64)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('very_challenging', 'Very Challenging')], default='moderate', max_length=20)),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('deadline', models.DateTimeField(blank=True, help_text='Task deadline if specified', null=True)),
                ('reasoning', models.TextField(blank=True, help_text='AI-generated reasoning for the estimate')),
                ('factors_considered', models.JSONField(default=list, help_text='List of factors considered in estimation')),
                ('recommended_approach', models.TextField(blank=True, help_text='AI-recommended study approach')),
                ('potential_obstacles', models.JSONField(default=list, help_text='Potential challenges identified')),
                ('time_breakdown', models.JSONField(default=dict, help_text='Breakdown of time allocation')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('actual_hours_spent', models.FloatField(blank=True, help_text='Actual time spent when completed', null=True)),
                ('accuracy_score', models.FloatField(blank=True, help_text='Estimation accuracy (0.0 to 1.0)', null=True)),
                ('student_feedback', models.TextField(blank=True, help_text='Student feedback on estimation quality')),
                ('suggested_start_time', models.DateTimeField(blank=True, null=True)),
                ('suggested_end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_estimations', to='MindMateAPP.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskEstimationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('accuracy', 'Estimation Accuracy'), ('difficulty', 'Task Difficulty Assessment'), ('obstacles', 'Unexpected Obstacles'), ('time_breakdown', 'Time Breakdown Accuracy'), ('general', 'General Feedback')], default='general', max_length=32)),
                ('rating', models.IntegerField(help_text='Rating from 1-5 (5 being excellent)')),
                ('comments', models.TextField(blank=True, help_text='Detailed feedback comments')),
                ('was_too_optimistic', models.BooleanField(default=False, help_text='Was the estimate too optimistic?')),
                ('was_too_pessimistic', models.BooleanField(default=False, help_text='Was the estimate too pessimistic?')),
                ('unexpected_difficulties', models.JSONField(default=list, help_text='Unexpected challenges encountered')),
                ('helpful_suggestions', models.JSONField(default=list, help_text='Which suggestions were most helpful')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='MindMateAPP.taskestimationrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('total_breaks_taken', models.IntegerField(default=0)),
                ('total_break_duration', models.DurationField(blank=True, null=True)),
                ('focus_quality_rating', models.IntegerField(default=3, help_text='Self-rated focus quality (1-5)')),
                ('energy_level_start', models.IntegerField(default=3, help_text='Energy level at start (1-5)')),
                ('energy_level_end', models.IntegerField(default=3, help_text='Energy level at end (1-5)')),
                ('satisfaction_rating', models.IntegerField(default=3, help_text='Satisfaction with work quality (1-5)')),
                ('study_location', models.CharField(blank=True, help_text='Where the study took place', max_length=128)),
                ('distractions_encountered', models.JSONField(default=list, help_text='List of distractions')),
                ('tools_used', models.JSONField(default=list, help_text='Study tools and resources used')),
                ('concepts_mastered', models.JSONField(default=list, help_text='Key concepts learned/mastered')),
                ('areas_needing_review', models.JSONField(default=list, help_text='Areas identified for further review')),
                ('follow_up_tasks', models.JSONField(default=list, help_text='Additional tasks identified')),
                ('student_notes', models.TextField(blank=True, help_text="Student's reflection on the session")),
                ('completion_challenges', models.TextField(blank=True, help_text='Challenges faced during completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_log', to='MindMateAPP.taskestimationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPerformanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_estimations', models.IntegerField(default=0)),
                ('average_accuracy_score', models.FloatField(default=0.5, help_text='Average estimation accuracy')),
                ('estimation_improvement_trend', models.FloatField(default=0.0, help_text='Improvement trend over time')),
                ('subject_performance_data', models.JSONField(default=dict, help_text='Performance data by subject')),
                ('task_type_performance', models.JSONField(default=dict, help_text='Performance data by task type')),
                ('typical_overestimation_factor', models.FloatField(default=1.0, help_text='How much student typically overestimates')),
                ('typical_underestimation_factor', models.FloatField(default=1.0, help_text='How much student typically underestimates')),
                ('consistency_score', models.FloatField(default=0.5, help_text="How consistent student's performance is")),
                ('learning_style_effectiveness', models.JSONField(default=dict, help_text='Effectiveness of different learning styles')),
                ('difficulty_preference_accuracy', models.JSONField(default=dict, help_text='Accuracy by difficulty preference')),
                ('preferred_study_times', models.JSONField(default=list, help_text='Most productive study time slots')),
                ('average_session_length', models.FloatField(default=2.0, help_text='Average effective study session length')),
                ('break_frequency_optimal', models.FloatField(default=0.25, help_text='Optimal break frequency')),
                ('recent_accuracy_score', models.FloatField(default=0.5)),
                ('recent_completion_rate', models.FloatField(default=0.8, help_text='Percentage of tasks completed as planned')),
                ('recent_feedback_score', models.FloatField(default=3.0, help_text='Average feedback rating (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_calculation', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_profile', to='MindMateAPP.student')),
            ],
            options={
                'verbose_name': 'Student Performance Profile',
                'verbose_name_plural': 'Student Performance Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='taskestimationrequest',
            index=models.Index(fields=['student', 'task_type'], name='MindMateAPP_student_42ff54_idx'),
        ),
        migrations.AddIndex(
            model_name='taskestimationrequest',
            index=models.Index(fields=['student', 'subject_area'], name='MindMateAPP_student_87aee1_idx'),
        ),
        migrations.AddIndex(
            model_name='taskestimationrequest',
            index=models.Index(fields=['status', 'created_at'], name='MindMateAPP_status_9eb19f_idx'),
        ),
    ]
