# Generated by Django 5.2.3 on 2025-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindMateAPP', '0005_taskestimationrequest_taskestimationfeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='vector_collection_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
